name: Deploy Low Codeh5
on: [push]
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USER}}  
          password: ${{secrets.SSH_PWD}} 
          script_stop: true
          script: |
            cd /
            cd nginx
            rm -rf h5-drap
            git clone git@github.com:wangjiang666/h5-drap.git -b ${{ github.ref_name }}
            cd h5-drap
            npm install
            npm run build